services:
  - type: web
    name: library-management-system
    env: docker
    plan: starter
    buildCommand: ./build.sh
    startCommand: java -jar target/library-management-system-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        value: jdbc:sqlite:/opt/render/project/src/data/library.db
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
    healthCheckPath: /actuator/health
    autoDeploy: true
    branch: main
    rootDir: /
    dockerfilePath: ./Dockerfile
