spring:
  application:
    name: library-management-system
  
  datasource:
    url: jdbc:sqlite:library.db
    driver-class-name: org.sqlite.JDBC
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        hbm2ddl:
          create_namespaces: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        
  security:
    user:
      name: admin
      password: admin123
      
server:
  port: 8080

logging:
  level:
    com.library.system: DEBUG
    org.springframework.security: DEBUG
