spring:
  application:
    name: library-management-system
  
  datasource:
    url: jdbc:sqlite:library.db?busy_timeout=5000&journal_mode=WAL&foreign_keys=on
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        hbm2ddl:
          create_namespaces: false
        jdbc:
          batch_size: 0
          use_get_generated_keys: false
        order_inserts: true
        order_updates: true

  # Avoid long-lived read transactions that can hold SQLite locks
  open-in-view: false
        
  security:
    user:
      name: admin
      password: admin123
      
server:
  port: 8080

logging:
  level:
    com.library.system: DEBUG
    org.springframework.security: DEBUG
